[package]
name = "market-data-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "chakra-market-data-worker"
path = "src/main.rs"

[dependencies]
market-snapshot = { path = "../market-snapshot" }
dex-adapters = { path = "../dex-adapters" }

tokio.workspace = true
reqwest.workspace = true
futures.workspace = true
async-trait.workspace = true
anyhow.workspace = true
serde_json.workspace = true
serde.workspace = true
hex.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
redis = { version = "1.2.1", features = ["aio", "tokio-comp"] }
tokio-tungstenite = { version = "0.24", features = ["connect", "native-tls"] }
