[package]
name = "Arc-dex-aggregator-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "TypeScript SDK is the primary client. This Rust crate is for internal testing."

[dependencies]
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
anyhow.workspace = true
tokio.workspace = true
